### ISSUE TITLE
Shared arguments can be further improved

### ISSUE THREAD

**Issue by Jonah1234567** [Kings-Distributed-Systems/Bifrost#36]
Currently the way shared arguments are submitted to a work function is in a form of a dictionary. This is how shared arguments is done for an image transformation demo with Bifrost:

```
shared_args = { 'flip_flag': flip, 'blur_flag': blur, 'crop_flag': crop, 'blurring_value': blurring_value, 'crop_values': crop_values, 'image_size': image_size, 'axis': axis  }

def work_function(input_slice, flip_flag, blur_flag, crop_flag, blurring_value, crop_values, image_size, axis):
# ...

# COMPUTE FOR
job = dcp.compute_for(input_set, work_function, shared_args)

```
There is a more UX friendly way to do this. We have started discussing solutions for this problem at Distributive but documenting this issue is good practice. The solution to the arguments issue for compute_for/work function should allow the user to pass their shared arguments as a list or something similar that is easier to use then a dictionary. There should be no need for the user to interact with their arguments when they are passing them.

**Comment by ccmcintyre-kingsds** [comment]
List format gets us in line with DCP's Compute API spec, and is more intuitive than requiring dicts; that's a good starting goal, and I'm attaching the "bug" label to mark our falling short of that. If we can support a UX for distributing Bifrost workloads that is even more flexible and intuitive, and fits in with work functions that take shared arguments and input slices in arbitrary order with respect to each other (the implicit goal of #39 "Passing in a function ..."), that would be an extremely cool enhancement.

**Comment by ccmcintyre-kingsds** [comment]
We will aim to support the following convention for the time being:
```job = dcp.compute_for( input_set, work_function, *args **kwargs )```
where:
- `input_set` is a list of parallel inputs, each of which will be passed into work_function as the very first argument
- `args` is a list/iterable of positional arguments, passed in subsequent to the input slice
- `kwargs` is a dict of keyword arguments, passed in after the positional arguments
Since all current Python DCP workloads or templates in the wild use only **kwargs, we'll have to do a little finessing of the parsing inside compute_for, to make sure we don't break anything; simply reversing the order of this API is not itself an acceptable solution for supporting the previous jobs, that would be far too out of sync with Python's conventions and user expectations.

In a future issue/MR, perhaps focused around existing issue #39 , we will explore enhancements to this that might include allowing the user to select (or somehow intuiting from the code and function call) which input(s) are intended to be distributed, from elements of args or kwargs or both, without concern for the current special order of the input_slice. Some avenues of exploration for this might be Python range types used together with DCP MultiRangeObjects, or clever under-the-hood usage of tuples, or even custom code decorators for the API.
